# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim
WORKDIR /app
COPY pyproject.toml uv.lock ./
RUN pip install --no-cache-dir pip && pip install --no-cache-dir .
COPY . .
CMD ["python","list_dict.py"]
